esphome:
  name: bathroomheater

  project:
    name: dasfoo.bathroomheater
    version: "1.0"

  includes:
  - zehnder.h

packages:
  device_base: !include templates/esp8266.yaml

dallas:
- pin: D1

sensor:
- platform: dallas
  address: 0x0401212E565C7428
  id: bathroom_heater_temperature

remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%
  id: heater_ir_transmitter

climate:
- platform: custom
  lambda: |-
    auto heater = new Zehnder();
    App.register_component(heater);
    heater->set_transmitter(id(heater_ir_transmitter));
    heater->add_temperature_sensor(id(bathroom_heater_temperature));
    return {heater};
  climates:
  - name: "Bathroom Heater"
    id: bathroom_heater

interval:
- interval: 1min
  then:
    # Periodically remind heater about the current setting.
    lambda: static_cast<Zehnder*>(id(bathroom_heater))->retransmit();
