esphome:
  name: bathroomheater
  platform: ESP8266
  board: nodemcuv2
  includes:
  - zehnder.h

logger:

web_server:
  port: 80

mqtt:
  broker: mqtt.lan

switch:
- platform: gpio
  pin:
    number: D4
    inverted: true
  restore_mode: ALWAYS_OFF
  name: "Bathroom Heater LED"

dallas:
- pin: D1

sensor:
- platform: dallas
  address: 0x0401212E565C7428
  name: "Bathroom Heater Temperature"

remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%
  id: heater_ir_transmitter

climate:
- platform: custom
  lambda: |-
    auto heater = new Zehnder();
    App.register_component(heater);
    heater->set_transmitter(id(heater_ir_transmitter));
    return {heater};
  climates:
  - name: "Bathroom Heater"
    id: bathroom_heater

interval:
- interval: 1min
  then:
    # Periodically remind heater about the current setting.
    lambda: static_cast<Zehnder*>(id(bathroom_heater))->retransmit();

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bathroomheater"
    password: !secret wifi_fallback_hotspot_password

captive_portal:
