esphome:
  name: bathroomheater
  friendly_name: "Bathroom heater"
  area: "Bathroom"

  project:
    name: dasfoo.bathroomheater
    version: "1.0"

external_components:
- source: components

packages:
  device_base: !include templates/esp8266.yaml
  sensor: !include templates/esp8266-vcc.yaml

one_wire:
- platform: gpio
  pin: D1

sensor:
- platform: dallas_temp
  address: 0x0401212E565C7428
  id: bathroom_heater_temperature

remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%
  id: heater_ir_transmitter

climate:
- platform: zehnder
  name: None
  id: bathroom_heater
  transmitter_id: heater_ir_transmitter
  temperature_sensor_id: bathroom_heater_temperature
