esphome:
  name: blinds
  friendly_name: "Blinds"
  area: "Entryway"

  project:
    name: dasfoo.blinds
    version: "3.0"

  libraries:
    - SPI
    - lsatan/SmartRC-CC1101-Driver-Lib

packages:
  device_base: !include templates/esp32-poe.yaml

external_components:
  # Path is relative to the main YAML file, not this device_base template!
  - source: components

cover:
  - name: "Office window"
    remote_id_offset: 0
    <<: &somfy_cover
      platform: somfy
      rf_pin: 4
      # Can be retrieved from MQTT server. Take the key with lowest integer value
      # from /$board/rolling_code/ path.
      remote_id_base: !secret somfy_remote_id_base

  - name: "Bedroom"
    remote_id_offset: 1
    <<: *somfy_cover
  - name: "Living Room side"
    remote_id_offset: 2
    <<: *somfy_cover
  - name: "Wardrobe"
    remote_id_offset: 3
    <<: *somfy_cover
  - name: "Child West door"
    remote_id_offset: 4
    <<: *somfy_cover
  - name: "Child West window"
    remote_id_offset: 5
    <<: *somfy_cover
  - name: "Hallway Stairs window"
    remote_id_offset: 6
    <<: *somfy_cover
  - name: "Kitchen window"
    remote_id_offset: 7
    <<: *somfy_cover
  - name: "Kitchen door"
    remote_id_offset: 8
    <<: *somfy_cover
  - name: "Living Room door"
    remote_id_offset: 9
    <<: *somfy_cover
  - name: "Living Room window"
    remote_id_offset: 10
    <<: *somfy_cover
  - name: "Child East window"
    remote_id_offset: 11
    <<: *somfy_cover
  - name: "Child East door"
    remote_id_offset: 12
    <<: *somfy_cover

  - platform: template
    name: "Wintergarten"
    device_class: awning
    optimistic: true
    assumed_state: true # always show both buttons
    stop_action:
      - switch.turn_off: wintergarten_deploy
      - switch.turn_off: wintergarten_retract
    open_action:
      - switch.turn_off: wintergarten_deploy
      - switch.turn_on: wintergarten_retract
      - delay: 35s
      - switch.turn_off: wintergarten_retract # TODO: check last action
    close_action:
      - switch.turn_off: wintergarten_retract
      - switch.turn_on: wintergarten_deploy
      - delay: 35s
      - switch.turn_off: wintergarten_deploy # TODO: check last action

switch:
  - platform: gpio
    pin: GPIO32
    id: wintergarten_deploy
    restore_mode: ALWAYS_OFF
    inverted: true

  - platform: gpio
    pin: GPIO33
    id: wintergarten_retract
    restore_mode: ALWAYS_OFF
    inverted: true
