esphome:
  name: boiler

  project:
    name: dasfoo.boiler
    version: "1.0"

packages:
  device_base: !include templates/esp8266.yaml

i2c:
  sda: D3
  scl: D4

font:
- file: "fonts/DejaVuSans.ttf"
  id: font_sans
  size: 20

display:
- platform: ssd1306_i2c
  model: "SSD1306 128x32"
  id: oled_display
  lambda: |-
    it.printf(
      4, 6,
      id(font_sans),
      "%.2f C",
      id(boiler_temperature).state);

    if (id(furnace_burning).state) {
      it.filled_circle(112, 16, 12);
    } else {
      it.circle(112, 16, 12);
    }

dallas:
- pin: D1

sensor:
- platform: dallas
  address: 0x133c2cf648f40728
  id: boiler_temperature
  name: "Boiler Temperature"
  filters:
  - offset: 3.3

- platform: adc
  pin: A0
  update_interval: 1s
  id: furnace_led_brightness

binary_sensor:
- platform: analog_threshold
  id: furnace_burning
  name: "Furnace Burning"
  sensor_id: furnace_led_brightness
  threshold: 0.7
  filters:
  - invert:
