esphome:
  name: boiler

  project:
    name: dasfoo.boiler
    version: "1.0"

esp8266:
  board: nodemcuv2

logger:

mqtt:
  broker: mqtt

dallas:
- pin: D1

sensor:
- platform: dallas
  address: 0x133c2cf648f40728
  name: "Boiler Temperature"
  filters:
  - offset: 3.3

- platform: adc
  pin: A0
  name: "Furnace LED brightness"
  update_interval: 1s
  id: furnace_led_brightness

binary_sensor:
- platform: analog_threshold
  name: "Furnace Burning"
  sensor_id: furnace_led_brightness
  threshold: 0.7
  filters:
  - invert:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ""
