esphome:
  name: btproxy
  name_add_mac_suffix: true
  friendly_name: "BTProxy"

  project:
    name: dasfoo.btproxy
    version: "1.0"

packages:
  device_base: !include templates/esp32-poe.yaml

  btproxy: !include templates/btproxy.yaml
  # Allow HA to use our proxy.
  api: !include templates/api.yaml
