esphome:
  name: btproxy
  name_add_mac_suffix: true
  friendly_name: "BTProxy"

  project:
    name: dasfoo.btproxy
    version: "1.0"

mqtt:
  # MQTT writes will have conflicting nodes because all our proxies have
  # the same name. API should be sufficient.
  enable_on_boot: false

packages:
  device_base: !include templates/esp32-poe.yaml

  btproxy: !include templates/btproxy.yaml
  # Allow HA to use our proxy.
  api: !include templates/api.yaml
