esphome:
  name: btproxy
  name_add_mac_suffix: true

  project:
    name: dasfoo.btproxy
    version: "1.0"

packages:
  device_base: !include templates/esp32-poe.yaml

# Allow HA to use our proxy.
# Don't enable MQTT as the device will be "discovered" twice.
api:

# Disable web component to save memory.
esp32_ble_tracker:
  scan_parameters:
    # Recommended scan intervals for esphome.
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
- platform: restart
  name: "btproxy Restart"
