substitutions:
  name: "car-charger"

esphome:
  friendly_name: "Car charger"

packages:
  device_base: !include templates/mystrom.yaml

time:
- platform: sntp
  on_time:
  # https://www.sak.ch/private/strom/strompreise2023
  #   SAK Schwachlast (T2):
  #     Montag bis Freitag: 00.00 bis 07.00 Uhr | 19.00 bis 24.00 Uhr
  #     Samstag bis Sonntag: 00.00 bis 24.00 Uhr
  - hours: 19
    minutes: 0
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 7
    minutes: 0
    seconds: 0
    days_of_week: MON-FRI
    then:
    - switch.turn_off: mystrom_relay
