# To bootstrap and then use OTA to flash firmware.

esphome:
  name: empty8266
  platform: ESP8266
  board: nodemcuv2

logger:

web_server:
  port: 80

switch:
- platform: gpio
  pin:
    number: D4
    inverted: true
  restore_mode: ALWAYS_OFF
  name: "LED"

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
