esphome:
  name: epaper
  platform: ESP32
  board: esp32doit-devkit-v1

# Enable logging
logger:

web_server:
  port: 80

font:
- file: 'AvalonQuest.ttf'
  id: avalon_quest
  size: 16

spi:
  mosi_pin: GPIO23
  clk_pin: GPIO18
  # wtf
  miso_pin: GPIO19

display:
  - platform: waveshare_epaper
    cs_pin: GPIO5
    dc_pin: GPIO17
    reset_pin: GPIO16
    busy_pin: GPIO4
    model: 2.13in
    rotation: 90°
    full_update_every: 30
    lambda: |-
      it.clear();
      it.print(10, 10, id(avalon_quest), "ABCD");
      it.print(10, 30, id(avalon_quest), "XXXX");
      it.print(10, 50, id(avalon_quest), "YYYY");
      it.print(10, 70, id(avalon_quest), "WHAT THE HELL");

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Epaper Fallback Hotspot"
    password: !secret wifi_fallback_hotspot_password

captive_portal:
