esphome:
  name: heating-og
  friendly_name: "Heating OG"
  area: "Bedroom"

  project:
    name: dasfoo.heating-og
    version: "1.0"

esp8266:
  board: esp12e
  # The board could reboot due to missing MQTT connection.
  #
  # We want it to be resilient and keep water circulating where
  # it was before the reboot. This is especially important while
  # on WiFi in a metal cage (poor connection quality).
  #
  # Heating itself is controlled centrally and can be shut off
  # independent of actual GPIO state of this board.
  restore_from_flash: true

packages:
  wifi: !include templates/wifi.yaml
  ota: !include templates/ota.yaml
  mqtt: !include templates/mqtt.yaml
  uptime: !include templates/uptime.yaml
  restart: !include templates/restart.yaml
  syslog: !include templates/syslog.yaml

logger:

switch:
  - platform: gpio
    pin: GPIO16
    name: "Shower"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO14
    name: "Bedroom"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO12
    name: "Wardrobe"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO13
    name: "Office and Hallway"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO15
    name: "Child West"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO00
    name: "Bathroom"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO04
    name: "Child East"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: GPIO05
    id: unused_relay8
    restore_mode: RESTORE_DEFAULT_OFF
