esphome:
  name: heating-og-new
  friendly_name: "Heating OG New"
  area: "Bedroom"

  project:
    name: dasfoo.heating-og
    version: "2.0"

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

packages:
  #wifi: !include templates/wifi.yaml
  ota: !include templates/ota.yaml
  mqtt: !include templates/mqtt.yaml
  uptime: !include templates/uptime.yaml
  restart: !include templates/restart.yaml
  syslog: !include templates/syslog.yaml

logger:

ethernet:
  type: JL1101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  power_pin: GPIO0
  phy_addr: 1
  domain: ""

text_sensor:
- platform: ethernet_info
  ip_address:
    name: "ESP chip IP (Ethernet)"
    icon: mdi:ip-network
  mac_address:
    name: "ESP chip MAC (Ethernet)"
    icon: mdi:expansion-card


sn74hc595: # write
  - id: 'sn74hc595_hub'
    clock_pin: GPIO14 # SRCLK
    data_pin: GPIO13 # SER
    latch_pin: GPIO15 # RCLK
    oe_pin: GPIO32 # OE
    sr_count: 8

# Individual outputs
switch:
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW0"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 0
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW1"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 1
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW2"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 2
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW3"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 3
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW4"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 4
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW5"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 5
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW6"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 6
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    name: "SW7"
    pin:
      sn74hc595: sn74hc595_hub
      # Use pin number 0
      number: 7
      inverted: false

