esphome:
  name: loud-siren
  friendly_name: "Loud siren"

  project:
    name: dasfoo.siren
    version: "1.0"

packages:
  device_base: !include templates/esp01s.yaml

button:
  - platform: template
    name: "Short beep"
    on_press:
      - switch.turn_on: relay
      - delay: 1ms
      - switch.turn_off: relay

  - platform: template
    name: "Beep"
    on_press:
      - switch.turn_on: relay
      - delay: 200ms
      - switch.turn_off: relay
