substitutions:
  name: "recirculation-pump"

packages:
  device_base: !include templates/mystrom.yaml

time:
- platform: sntp
  on_time:
  - hours: 4
    minutes: 30
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 20
    minutes: 0
    seconds: 0
    then:
    - switch.turn_off: mystrom_relay
