substitutions:
  name: "outdoor-equipment"
  friendly_name: "Outdoor equipment"

esphome:
  area: "Backyard"

packages:
  device_base: !include templates/mystrom.yaml

time:
- platform: sntp
  servers: [eye]
  on_time:

  #
  # Pool pump
  #
  - hours: 15
    minutes: 35
    seconds: 0
    months: APR-OCT
    then:
    - switch.turn_on: mystrom_relay
  - hours: 21
    minutes: 55
    seconds: 0
    months: APR-OCT
    then:
    - switch.turn_off: mystrom_relay
