substitutions:
  name: "outdoor-equipment"
  friendly_name: "Outdoor equipment"

esphome:
  area: "Backyard"

packages:
  device_base: !include templates/mystrom.yaml

time:
- platform: sntp
  servers: [eye]
  on_time:

  #
  # Pool pump: requires 6h of pumping daily, of which 3h
  #            run with saltwater system enabled, usually
  #            17:00 - 20:00 to balance between lower sunlight
  #            (for chlorine generation) and lower humidity
  #            (for ozone generation).
  #
  - hours: 15
    minutes: 35
    seconds: 0
    months: APR-OCT
    then:
    - switch.turn_on: mystrom_relay
  - hours: 21
    minutes: 35
    seconds: 0
    months: APR-OCT
    then:
    - switch.turn_off: mystrom_relay
