substitutions:
  name: "pool-pump"

esphome:
  friendly_name: "Pool pump"

packages:
  device_base: !include templates/mystrom.yaml

time:
- platform: sntp
  on_time:
  - hours: 15
    minutes: 35
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 21
    minutes: 55
    seconds: 0
    then:
    - switch.turn_off: mystrom_relay
