substitutions:
  name: "recirculation-pump"

esphome:
  friendly_name: "Recirculation pump"
  area: "Workshop"

packages:
  device_base: !include templates/mystrom.yaml

time:
- platform: sntp
  on_time:
  # Heating schedule is 5AM to 8PM. Judging by the burner state, it means that
  # by 5AM the water is expected to be hot (60C) and at 8PM it's expected to be
  # still hot as well (within the normal range of 56-60C).
  #
  # So the actual heating will start earlier, and so should recirculation.
  - hours: 4
    minutes: 30
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  # Then, pump every 30 minutes for 3 minutes long.
  - hours: "5-20"
    minutes: "0,30"
    seconds: "0"
    then:
    - switch.turn_off: mystrom_relay
  - hours: "5-19"
    minutes: "27,57"
    seconds: "0"
    then:
    - switch.turn_on: mystrom_relay
