substitutions:
  name: "recirculation-pump"

esphome:
  friendly_name: "Recirculation pump"

packages:
  device_base: !include templates/mystrom.yaml

time:
- platform: sntp
  on_time:
  # Heating schedule is 5AM to 8PM. Judging by the burner state, it means that
  # by 5AM the water is expected to be hot (60C) and at 8PM it's expected to be
  # still hot as well (within the normal range of 56-60C).
  #
  # So the actual heating will start earlier, and so should recirculation.
  - hours: 4
    minutes: 30
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 5
    minutes: 0
    seconds: 0
    then:
    - switch.turn_off: mystrom_relay
  # Set up several periods of recirculation pump activity to keep boiler water
  # circulating, but not at too high expense of cooling it down through the
  # pipeline.
  - hours: 7
    minutes: 00
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 7
    minutes: 30
    seconds: 0
    then:
    - switch.turn_off: mystrom_relay

  - hours: 10
    minutes: 00
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 10
    minutes: 30
    seconds: 0
    then:
    - switch.turn_off: mystrom_relay

  - hours: 13
    minutes: 00
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 14
    minutes: 0
    seconds: 0
    then:
    - switch.turn_off: mystrom_relay

  - hours: 16
    minutes: 00
    seconds: 0
    then:
    - switch.turn_on: mystrom_relay
  - hours: 17
    minutes: 0
    seconds: 0
    then:
    - switch.turn_off: mystrom_relay
