esphome:
  name: ruuvi

  project:
    name: dasfoo.ruuvi
    version: "1.0"

packages:
  device_base: !include templates/esp32-poe.yaml

# Required for ruuvitag.
esp32_ble_tracker:

sensor:
- platform: ruuvitag
  mac_address: CE:43:F8:76:DF:2E
  humidity:
    name: "Garage Humidity"
  temperature:
    name: "Garage Temperature"
  pressure:
    name: "Garage Pressure"
  acceleration:
    name: "Garage Acceleration"
  battery_voltage:
    name: "Garage Sensor Battery Voltage"
- platform: ruuvitag
  mac_address: C9:3A:C7:42:BD:47
  humidity:
    name: "Outdoor West Humidity"
  temperature:
    name: "Outdoor West Temperature"
  pressure:
    name: "Outdoor West Pressure"
  acceleration:
    name: "Outdoor West Acceleration"
  battery_voltage:
    name: "Outdoor West Sensor Battery Voltage"
