esphome:
  name: ruuvi

  project:
    name: dasfoo.ruuvi
    version: "1.0"

esp32:
  board: esp32-poe
  # Required for BLE.
  framework:
    type: esp-idf

# Enable logging
logger:

mqtt:
  broker: homeassistant
  username: esphome
  password: !secret mqtt_password

# Required for ruuvitag.
esp32_ble_tracker:

sensor:
- platform: ruuvitag
  mac_address: CE:43:F8:76:DF:2E
  humidity:
    name: "Garage Humidity"
  temperature:
    name: "Garage Temperature"
  pressure:
    name: "Garage Pressure"
  acceleration:
    name: "Garage Acceleration"
  battery_voltage:
    name: "Garage Sensor Battery Voltage"
- platform: ruuvitag
  mac_address: C9:3A:C7:42:BD:47
  humidity:
    name: "Outdoor West Humidity"
  temperature:
    name: "Outdoor West Temperature"
  pressure:
    name: "Outdoor West Pressure"
  acceleration:
    name: "Outdoor West Acceleration"
  battery_voltage:
    name: "Outdoor West Sensor Battery Voltage"

ota:
  password: !secret ota_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
