esphome:
  name: ruuvi
  platform: ESP32
  board: esp32doit-devkit-v1

# Enable logging
logger:

mqtt:
  broker: mqtt

web_server:
  port: 80

# Required for ruuvitag.
esp32_ble_tracker:

sensor:
- platform: ruuvitag
  mac_address: CE:43:F8:76:DF:2E
  humidity:
    name: "Garage Humidity"
  temperature:
    name: "Garage Temperature"
  pressure:
    name: "Garage Pressure"
  acceleration:
    name: "Garage Acceleration"
  battery_voltage:
    name: "Garage Sensor Battery Voltage"
- platform: ruuvitag
  mac_address: C9:3A:C7:42:BD:47
  humidity:
    name: "Outdoor West Humidity"
  temperature:
    name: "Outdoor West Temperature"
  pressure:
    name: "Outdoor West Pressure"
  acceleration:
    name: "Outdoor West Acceleration"
  battery_voltage:
    name: "Outdoor West Sensor Battery Voltage"

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ruuvi Fallback Hotspot"
    password: !secret wifi_fallback_hotspot_password

captive_portal:
