esphome:
  name: wardrobe

  project:
    name: dasfoo.wardrobe
    version: "1.0"

esp8266:
  board: nodemcuv2

logger:

mqtt:
  broker: mqtt

dallas:
- pin: D4

sensor:
- platform: dallas
  address: 0x6a0316643959ff28
  name: "Aquarium Temperature"

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ""
