esp32:
  board: esp32-poe

status_led:
  pin: GPIO2

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: ""

text_sensor:
- platform: ethernet_info
  ip_address:
    name: "Device IP (Ethernet)"
  mac_address:
    name: "Device MAC (Ethernet)"

sensor:
- platform: esp32_hall
  name: "ESP chip Hall Effect strength"

logger:

packages:
  ota: !include ota.yaml
  mqtt: !include mqtt.yaml
  uptime: !include uptime.yaml
  restart: !include restart.yaml
