esp32:
  board: esp32-poe
  # Required for BLE.
  framework:
    type: esp-idf

status_led:
  pin: GPIO2

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: ""

logger:

packages:
  ota: !include ota.yaml
  mqtt: !include mqtt.yaml

button:
- platform: restart
  name: "ESP chip restart"
  entity_category: diagnostic
