sensor:
- platform: wifi_signal
  name: "WiFi signal"

text_sensor:
- platform: wifi_info
  mac_address:
    name: "Device MAC"
  ip_address:
    name: "Device IP"
  bssid:
    name: "Connected to BSSID"
    filters:
    - to_upper
    - substitute: !secret wifi_ap_lookup

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ""
