sensor:
- platform: wifi_signal
  name: "ESP chip WiFi signal"

text_sensor:
- platform: wifi_info
  mac_address:
    name: "ESP chip MAC"
  ip_address:
    name: "ESP chip IP"
  bssid:
    name: "ESP chip connected to BSSID"
    filters:
    - to_upper
    - substitute: !secret wifi_ap_lookup

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ""
