# To bootstrap and then use OTA to flash firmware.

esp32:
  board: esp32doit-devkit-v1

esphome:
  name: empty32
  name_add_mac_suffix: true

packages:
  wifi: !include ../templates/wifi.yaml
  ota: !include ../templates/ota.yaml
