# To bootstrap and then use OTA to flash firmware.

esp8266:
  board: nodemcuv2

esphome:
  name: empty8266
  name_add_mac_suffix: true

packages:
  wifi: !include ../templates/wifi.yaml
  ota: !include ../templates/ota.yaml
