# To bootstrap and then use OTA to flash firmware.

esphome:
  name: empty8266
  name_add_mac_suffix: true

esp8266:
  board: nodemcuv2

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ""
